### PR TITLE
site: use tagName field for generating source code links

### PR DESCRIPTION
**Pull request by callmehiphop**
Closes https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1602

**Demo:**
- [site](http://callmehiphop.github.io/gcloud-node/#/docs/bigquery/0.1.2/bigquery)
- [code](https://github.com/callmehiphop/gcloud-node/tree/gh-pages)

### CODE REVIEW

**Comment by callmehiphop** [comment]
@quartzmo @dwsupplee @jdpedrie PTAL!

**Comment by jdpedrie** [comment]
I think it's good for us. I pulled your changes locally and tried browsing the docs for `master` and `v0.8.0` and it works fine. If there is any other tests I should run let me know!

**Comment by quartzmo** [comment]
@callmehiphop Testing it now!

**Comment by quartzmo** [comment]
@callmehiphop I get an error locally when trying to navigate to code in the umbrella package. Can you put up a demo so that I can try to reproduce?

**Comment by quartzmo** [comment]
@callmehiphop The error I run into locally is that sub-directory for the "individual package" is missing from the path. I'll try to deploy to and recreate on my own gh-pages.

**Comment by callmehiphop** [comment]
@quartzmo sorry I didn't get back to you sooner, but I pushed a demo with the Node.js JSON, I've updated the PR overview with links!

**Comment by quartzmo** [comment]
@callmehiphop Thanks! Your demo seems to work great. I'm pretty sure the problem is something I need to change in JSON generation, so feel free to merge this PR.

**Comment by callmehiphop** [comment]
Cool, thanks @quartzmo!

**Pull request merged**
