### PR TITLE
site: adding .net to language switcher

### PR DESCRIPTION
**Pull request by callmehiphop**
Relates to #151 

This adds .NET to the language switcher.

[Demo!](http://callmehiphop.github.io/gcloud-node/#/)

### CODE REVIEW

**Comment by callmehiphop** [comment]
@quartzmo @dwsupplee I think you guys will also need this update, so a quick peek would be appreciated :)

/cc @jgeewax

**Comment by dwsupplee** [comment]
Looks good :)

**Comment by quartzmo** [comment]
LGTM, and thanks for always providing a demo.

**Comment by callmehiphop** [comment]
Woo! Thanks guys :)

**Pull request merged**
