### PR TITLE
site: Update docs.route otherwise to preserve query string

### PR DESCRIPTION
**Pull request by quartzmo**
Preserve query string in otherwise block redirects.

[fixes GoogleCloudPlatform/google-cloud-ruby#1610]

### CODE REVIEW

**Comment by quartzmo** [comment]
I think there may be some issue with the Travis CI build. Running `./deploy-docs.sh` passes for me locally.

**Comment by callmehiphop** [comment]
@quartzmo yeah, runs fine locally for me as well.

**Comment by quartzmo** [comment]
@callmehiphop Will the site deploy fail as well?

**Comment by callmehiphop** [comment]
Probably, I think you'll need to manually commit it until I get around to fixing CI :(

**Comment by quartzmo** [comment]
OK, thanks, I'll do a manual "deploy" for now. Should I open an issue for CI, or do you want to?

**Comment by callmehiphop** [comment]
I opened https://github.com/GoogleCloudPlatform/gcloud-common/issues/228!

**Pull request merged**
