### PR TITLE
site: create anchor directive

### PR DESCRIPTION
**Pull request by callmehiphop**
Relates to https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/913

### CODE REVIEW

**Comment by callmehiphop** [comment]
@quartzmo PTAL!

**Comment by quartzmo** [comment]
Nice having the spec to show it working. I'll pull the branch and try it now, but pretty clear that it works!

**Comment by quartzmo** [comment]
@callmehiphop The links work great internally, but external URLs do not bring me to the anchor, just the top of the page. Local example:

http://localhost:3000/#/docs/google-cloud-logging/master/google/cloud/logging?section=#exporting-log-entries

Should we worry about this?

**Comment by callmehiphop** [comment]
@quartzmo I think it should be http://localhost:3000/#/docs/google-cloud-logging/master/google/cloud/logging?section=exporting-log-entries

**Comment by quartzmo** [comment]
Ok, that's good:`?section=exporting-log-entries` does work, the problem now is just that when I click the internal anchor link, the browser bar displays `?section=#exporting-log-entries`. If I were trying to share the location, I would naturally copy and paste that, resulting in a broken link.

**Comment by callmehiphop** [comment]
So just to clarify, your HTML resembles the following

```html
<a data-anchor="#exporting-log-entries">Link Text</a>
```

?

**Comment by callmehiphop** [comment]
@quartzmo I added a new commit + test to ignore hash characters. PTAL

**Comment by quartzmo** [comment]
Aha, yes! (I just manually changed the `href` to `data-anchor`). I removed the `#` and it's good. But nice that you updated the code to prevent the issue...

**Comment by quartzmo** [comment]
I tested the update, works great for me now, with or without a hash in the value.

I'm ready to merge after build is green. Should my merge commit close #137? What about #40?

**Comment by callmehiphop** [comment]
I think we can safely close #137, but I would leave #40 open because we don't generate the clickable anchors for the user yet.

**Comment by quartzmo** [comment]
Thanks @callmehiphop!

**Comment by callmehiphop** [comment]
@quartzmo np!!

**Pull request merged**
